version: "3"

volumes:
  data:

services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

    ports:
      - "3000:3000"
    volumes:
      - ".:/rails-docker-mysql"
    environment:
      - "DATABASE_PASSWORD=password"
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: mysql
    volumes:
      - "data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
