version: "3"

volumes:
  data:

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/rails-docker-mysql"
    environment:
      - "DATABASE_PASSWORD=password"
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql
    volumes:
      - "data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
